FROM oven/bun:1.3.1 AS deps
WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
 && rm -rf /var/lib/apt/lists/*

COPY bun.lock package.json turbo.json ./
COPY packages ./packages
COPY apps ./apps

RUN bun install --ignore-scripts

RUN bunx prisma generate --schema=packages/db/prisma/schema.prisma

ENTRYPOINT []
CMD [ "true" ]