FROM upsite-deps:latest
WORKDIR /app

ENV DATABASE_URL="postgres://postgres:mysecret@postgres:5432/postgres"

COPY packages/db/prisma.config.ts /app/packages/db/prisma.config.ts

CMD ["bunx", "prisma", "migrate", "deploy", "--config=/app/packages/db/prisma.config.ts"]