FROM oven/bun:latest

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json bun.lock* ./
COPY turbo.json ./

COPY packages/db ./package/db
COPY apps/server ./apps/server

RUN bun install

WORKDIR /app/package/db

RUN bunx prisma generate

EXPOSE 8080

CMD [ "bun", "run", "index.ts" ]