FROM oven/bun:latest

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json bun.lock* ./
COPY turbo.json ./

COPY packages ./packages
COPY apps ./apps

RUN bun install --frozen-lockfile

WORKDIR /app/packages/db

RUN bunx prisma generate

WORKDIR /app/apps/producer

CMD ["bun", "run", "index.ts"]