FROM oven/bun:latest

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json bun.lock* ./
COPY turbo.json ./

COPY packages ./packages
COPY apps ./apps

RUN bun install --frozen-lockfile

WORKDIR /app/apps/web

RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start" ]